@Transportation_Management_System_Tracking_Service_REST_API_HostAddress = http://localhost:5046

GET {{Transportation_Management_System_Tracking_Service_REST_API_HostAddress}}/weatherforecast/
Accept: application/json

###
